//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanStore
    {
        public int Id { get; set; }
        public string DataPName { get; set; }
        public string LoanData { get; set; }
        public System.DateTime LoadedDate { get; set; }
        public string AnalyzedDataPName { get; set; }
    }
}
